stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  FRONTEND_IMAGE: pradyumnajkumar/lib-frontend
  BACKEND_IMAGE: pradyumnajkumar/lib-backend

build_and_push_images:
  stage: build
  image: docker:27
  services:
    - docker:27-dind
  before_script:
    - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_TOKEN"
  script:
    - docker build -t "$FRONTEND_IMAGE:$CI_COMMIT_SHORT_SHA" -t "$FRONTEND_IMAGE:latest" ./frontend
    - docker build -t "$BACKEND_IMAGE:$CI_COMMIT_SHORT_SHA" -t "$BACKEND_IMAGE:latest" ./backend
    - docker push "$FRONTEND_IMAGE:$CI_COMMIT_SHORT_SHA"
    - docker push "$FRONTEND_IMAGE:latest"
    - docker push "$BACKEND_IMAGE:$CI_COMMIT_SHORT_SHA"
    - docker push "$BACKEND_IMAGE:latest"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
